FROM openjdk:8-jdk-alpine

RUN apk add gradle libpcap npm

COPY ./ /app/

WORKDIR /app/frontend

RUN npm install && npm run build

RUN cp -rf ./dist/* ../src/main/resources/static/

WORKDIR /app/

RUN gradle --no-daemon build

RUN cp build/libs/packmate-*.jar app.jar

ENV DB_USER ${PACKMATE_DB_USER:-packmate}
ENV DB_PASSWORD ${PACKMATE_DB_PASSWORD:-packmate_secret_password}
ENV DB_NAME ${PACKMATE_DB_DB:-packmate}
ENV LOCAL_IP ${PACKMATE_LOCAL_IP:-192.168.79.131}
ENV WEB_LOGIN ${PACKMATE_WEB_LOGIN:-BinaryBears}
ENV WEB_PASSWORD ${PACKMATE_WEB_PASSWORD:-123456}

EXPOSE 65000:65000

CMD ./start.sh
