FROM openjdk:13-jdk-alpine

RUN apk add libpcap npm

COPY ./ /app/

WORKDIR /app/frontend/

RUN npm install && npm run build

RUN mkdir -p ../src/main/resources/static/ \
	&& cp -rf ./dist/* ../src/main/resources/static/

WORKDIR /app/

RUN ./gradlew --no-daemon build

RUN cp build/libs/packmate-*.jar app.jar

EXPOSE 65000:65000
