FROM postgres:13.3-alpine

ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_DB

ENV POSTGRES_USER ${POSTGRES_USER}
ENV POSTGRES_PASSWORD ${POSTGRES_PASSWORD}
ENV POSTGRES_DB ${POSTGRES_DB}

COPY docker/postgresql.conf /tmp/postgresql.conf
COPY docker/update_db_config.sh /docker-entrypoint-initdb.d/_update_db_config.sh

EXPOSE 65001:65001
